---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration
  template: src=wordpress.conf dest=/etc/nginx/sites-available/wordpress
  notify: restart nginx

- name: Remove default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
