---
- name: Install MySQL server
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present login_user=root login_password=""

- name: Create mysql user
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL
    login_user=root
    login_password=""
