---
- name: Install php extensions
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-mysql
    - php5-gd
    - libssh2-php

- name: Disable default pool
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm
